import React, { useState, useEffect } from 'react';
import { StyleSheet, View, TouchableOpacity, SafeAreaView, TextInput, ScrollView, ActivityIndicator, Alert, Modal, Image, ImageBackground } from 'react-native';
import { useRouter } from 'expo-router';
import { LinearGradient } from 'expo-linear-gradient';
import { CameraView, useCameraPermissions } from 'expo-camera';
import * as ImagePicker from 'expo-image-picker';
import { ThemedText } from '@/components/themed-text';

// @ts-ignore
import { db } from '../../firebaseConfig';
import { collection, addDoc, serverTimestamp, doc, updateDoc, increment, onSnapshot } from "firebase/firestore";
import { LocationPicker } from '../(tabs)/LocationPicker';

export default function MerchantScreen() {
  const router = useRouter();
  
  // Real-time Green Points State
  const [greenPoints, setGreenPoints] = useState(0);

  // Form States
  const [foodName, setFoodName] = useState('');
  const [quantity, setQuantity] = useState('');
  const [image, setImage] = useState<string | null>(null);
  const [isPosting, setIsPosting] = useState(false);

  // Location States
  const [locationModalVisible, setLocationModalVisible] = useState(false);
  const [coordinates, setCoordinates] = useState<{latitude: number, longitude: number} | null>(null);

  // Scanner States
  const [permission, requestPermission] = useCameraPermissions();
  const [isScanning, setIsScanning] = useState(false);
  const [scanned, setScanned] = useState(false);

  // 1. Real-time Listener for Green Points
  useEffect(() => {
    const userRef = doc(db, "users", "Sarikha_Demo_Global");
    const unsub = onSnapshot(userRef, (snapshot) => {
      if (snapshot.exists()) {
        setGreenPoints(snapshot.data().greenPoints || 0);
      }
    });
    return () => unsub();
  }, []);

  const pickImage = async () => {
    const { status } = await ImagePicker.requestCameraPermissionsAsync();
    if (status !== 'granted') {
      Alert.alert("Permission Required", "Allow camera access to upload food photos.");
      return;
    }
    let result = await ImagePicker.launchCameraAsync({
      allowsEditing: true,
      aspect: [4, 3],
      quality: 0.5,
    });
    if (!result.canceled) setImage(result.assets[0].uri);
  };

  // 2. Scanner Logic to give Green Points
  // This scans the QR code generated by the Volunteer's phone
  const handleBarCodeScanned = async ({ data }: { data: string }) => {
    setScanned(true);
    setIsScanning(false);
    
    try {
      // The 'data' from the QR code is the Mission ID (Listing ID)
      const missionId = data;
      const foodRef = doc(db, "listings", missionId);
      const userRef = doc(db, "users", "Sarikha_Demo_Global");

      // Update Firebase: Mark as delivered and award points
      await updateDoc(foodRef, { 
        status: "delivered",
        deliveredAt: serverTimestamp() 
      });

      // Merchants earn 500 points for bulk missions!
      await updateDoc(userRef, { 
        greenPoints: increment(500), 
        totalImpact: increment(1) // Number of successful rescues
      });

      Alert.alert("Pickup Verified! 🌿", "500 Green Points added to your business profile. Thank you for saving a meal!");
    } catch (error) {
      Alert.alert("Verification Failed", "This QR code is invalid or has already been used.");
    }
  };

  // 3. Unified Post Logic with 20+ Validation
  const handlePost = async () => {
    if (!foodName || !quantity || !image || !coordinates) {
      Alert.alert("Missing Info", "Please provide a photo, food name, quantity, and pickup location.");
      return;
    }

    const amount = parseInt(quantity);
    
    // STRICT VALIDATION: Only 10+ allowed for Merchants
    if (isNaN(amount) || amount < 10) {
      Alert.alert(
        "Low Quantity Detected", 
        "Merchant accounts are reserved for bulk surplus (10+ packets). For smaller donations, please use the Individual Donor portal."
      );
      return;
    }

    setIsPosting(true);
    try {
      await addDoc(collection(db, "listings"), {
        foodName: foodName.trim(),
        quantity: amount,
        foodImage: image,
        locationCoords: coordinates,
        status: "available",
        role: "merchant",
        priority: "Critical", // This triggers the Red Badge and AI Priority in Volunteer View
        ownerId: "Sarikha_Demo_Global",
        createdAt: serverTimestamp(),
      });

      Alert.alert("Impact Registered! 🌿", "Your bulk surplus is now a Critical Priority mission for our volunteers.");
      
      // Reset form
      setFoodName(''); 
      setQuantity(''); 
      setImage(null); 
      setCoordinates(null);
    } catch (error: any) {
      Alert.alert("Post Failed", error.message);
    } finally {
      setIsPosting(false);
    }
  };

  const startScanner = async () => {
    if (!permission?.granted) {
      const { granted } = await requestPermission();
      if (!granted) return;
    }
    setScanned(false);
    setIsScanning(true);
  };

  return (
    <View style={{ flex: 1 }}>
      <LinearGradient colors={['#FFFEF9', '#E8F8F5']} style={StyleSheet.absoluteFill} />
      
      <ImageBackground source={require('../../assets/images/6530.jpg')} style={styles.absoluteBG} resizeMode="cover">
        <SafeAreaView style={styles.container}>
          <ScrollView contentContainerStyle={styles.scrollContent} showsVerticalScrollIndicator={false}>
            
            {/* GREEN POINTS DASHBOARD */}
            <View style={styles.impactCard}>
              <LinearGradient colors={['#2E9081', '#1A242F']} style={styles.impactGradient}>
                <View style={styles.statBox}>
                  <ThemedText style={styles.statLabel}>BUSINESS SUSTAINABILITY SCORE</ThemedText>
                  <ThemedText style={styles.statNumber}>🌿 {greenPoints}</ThemedText>
                </View>
              </LinearGradient>
            </View>

            <View style={styles.headerSection}>
              <View style={styles.badge}><ThemedText style={styles.badgeText}>OFFICIAL MERCHANT</ThemedText></View>
              <ThemedText style={styles.title}>Bulk Recovery</ThemedText>
              <ThemedText style={styles.subtitle}>List surplus or scan to verify volunteer pickup.</ThemedText>
            </View>

            <TouchableOpacity style={styles.scanBtn} onPress={startScanner}>
              <ThemedText style={styles.scanBtnText}>📸 Scan Volunteer QR</ThemedText>
            </TouchableOpacity>

            <View style={styles.divider}>
              <View style={styles.line} /><ThemedText style={styles.dividerText}>POST NEW SURPLUS</ThemedText><View style={styles.line} />
            </View>

            <View style={styles.formContainer}>
              <TouchableOpacity style={styles.photoUploadBox} onPress={pickImage}>
                {image ? (
                  <Image source={{ uri: image }} style={styles.previewImage} />
                ) : (
                  <View style={{ alignItems: 'center' }}>
                    <View style={styles.iconCircle}><ThemedText style={styles.icon}>🏢</ThemedText></View>
                    <ThemedText style={styles.uploadText}>Capture Food Photo</ThemedText>
                  </View>
                )}
              </TouchableOpacity>

              <View style={styles.inputGroup}>
                <ThemedText style={styles.label}>Dish Name</ThemedText>
                <TextInput 
                  style={styles.input} 
                  placeholder="e.g. 50kg Chicken Biryani" 
                  placeholderTextColor="#999"
                  value={foodName} 
                  onChangeText={setFoodName} 
                />
              </View>

              <View style={styles.inputGroup}>
                <ThemedText style={styles.label}>Quantity (Meals)</ThemedText>
                <TextInput 
                  style={styles.input} 
                  placeholder="Minimum 10 packets" 
                  placeholderTextColor="#999"
                  keyboardType="numeric"
                  value={quantity} 
                  onChangeText={setQuantity} 
                />
              </View>

              <TouchableOpacity 
                style={[styles.locationBtn, coordinates && styles.locationSet]} 
                onPress={() => setLocationModalVisible(true)}
              >
                <ThemedText style={[styles.locationBtnText, coordinates && { color: '#FFF' }]}>
                  {coordinates ? '📍 Pickup Point Set' : '🗺️ Select Pickup Location'}
                </ThemedText>
              </TouchableOpacity>

              {isPosting ? (
                <ActivityIndicator size="large" color="#2E9081" />
              ) : (
                <TouchableOpacity style={styles.postBtn} onPress={() => router.push('/dashboard')}>
                  <ThemedText style={styles.postBtnText}>Post as Critical Mission →</ThemedText>
                </TouchableOpacity>
              )}
            </View>

            <TouchableOpacity onPress={() => router.push('/dashboard')} style={styles.backBtn}>
              <ThemedText style={styles.backBtnText}>← Switch Account Type</ThemedText>
            </TouchableOpacity>
          </ScrollView>
        </SafeAreaView>
      </ImageBackground>

      <LocationPicker 
        visible={locationModalVisible} 
        onClose={() => setLocationModalVisible(false)} 
        onLocationSelect={(coords: any) => setCoordinates(coords)}
      />

      <Modal visible={isScanning} animationType="slide">
        <View style={styles.scannerContainer}>
          <CameraView
            onBarcodeScanned={scanned ? undefined : handleBarCodeScanned}
            barcodeScannerSettings={{ barcodeTypes: ["qr"] }}
            style={StyleSheet.absoluteFillObject}
          />
          <View style={styles.overlay}>
            <View style={styles.scanFrame} />
            <TouchableOpacity style={styles.closeScanner} onPress={() => setIsScanning(false)}>
              <ThemedText style={styles.closeScannerText}>Cancel</ThemedText>
            </TouchableOpacity>
          </View>
        </View>
      </Modal>
    </View>
  );
}

const styles = StyleSheet.create({
  absoluteBG: { flex: 1, width: '100%', height: '100%' },
  container: { flex: 1 },
  scrollContent: { paddingHorizontal: 25, paddingVertical: 40, alignItems: 'center' },
  headerSection: { marginBottom: 20, alignItems: 'center' },
  impactCard: { width: '100%', borderRadius: 25, overflow: 'hidden', marginBottom: 20, elevation: 5 },
  impactGradient: { padding: 25, alignItems: 'center' },
  statBox: { alignItems: 'center' },
  statLabel: { fontSize: 10, color: '#BDC3C7', fontWeight: '800', letterSpacing: 1 },
  statNumber: { fontSize: 32, color: '#FFF', fontWeight: '900', marginTop: 5 },
  badge: { backgroundColor: 'rgba(209, 242, 235, 0.9)', paddingHorizontal: 12, paddingVertical: 4, borderRadius: 20, marginBottom: 10 },
  badgeText: { color: '#2E9081', fontSize: 10, fontWeight: '800', textTransform: 'uppercase' },
  title: { fontSize: 32, color: '#1A242F', fontWeight: '900' },
  subtitle: { fontSize: 14, color: '#1A242F', textAlign: 'center', fontWeight: '600' },
  scanBtn: { backgroundColor: '#1A242F', padding: 15, borderRadius: 18, alignItems: 'center', width: '80%', alignSelf: 'center', elevation: 2 },
  scanBtnText: { color: '#FFF', fontWeight: '800', fontSize: 14 },
  divider: { flexDirection: 'row', alignItems: 'center', marginVertical: 25, width: '100%' },
  line: { flex: 1, height: 1, backgroundColor: 'rgba(0,0,0,0.2)' },
  dividerText: { marginHorizontal: 10, fontSize: 10, color: '#1A242F', fontWeight: '900' },
  formContainer: { width: '100%', maxWidth: 400, gap: 20, backgroundColor: 'rgba(255, 255, 255, 0.9)', padding: 20, borderRadius: 30, elevation: 5 },
  photoUploadBox: { backgroundColor: '#FFF', height: 140, borderRadius: 25, borderWidth: 2, borderColor: '#2E9081', borderStyle: 'dashed', justifyContent: 'center', alignItems: 'center', overflow: 'hidden' },
  previewImage: { width: '100%', height: '100%' },
  iconCircle: { width: 44, height: 44, borderRadius: 22, backgroundColor: '#E8F8F5', justifyContent: 'center', alignItems: 'center', marginBottom: 8 },
  icon: { fontSize: 20 },
  uploadText: { fontSize: 13, fontWeight: '700', color: '#1A242F' },
  inputGroup: { gap: 8 },
  label: { fontSize: 13, fontWeight: '800', color: '#1A242F', marginLeft: 5 },
  input: { backgroundColor: '#F0F0F0', padding: 15, borderRadius: 15, fontSize: 15, color: '#000' },
  locationBtn: { backgroundColor: '#FFF', borderWidth: 1, borderColor: '#2E9081', padding: 15, borderRadius: 15, alignItems: 'center', marginTop: 5 },
  locationSet: { backgroundColor: '#2E9081' },
  locationBtnText: { fontWeight: '800', color: '#2E9081', fontSize: 14 },
  postBtn: { backgroundColor: '#2E9081', paddingVertical: 18, borderRadius: 20, alignItems: 'center', width: '100%', marginTop: 10 },
  postBtnText: { color: '#FFF', fontWeight: '900', fontSize: 16 },
  backBtn: { marginTop: 25, backgroundColor: 'rgba(255,255,255,0.8)', paddingHorizontal: 20, paddingVertical: 10, borderRadius: 20 },
  backBtnText: { color: '#1A242F', fontWeight: '700' },
  scannerContainer: { flex: 1, backgroundColor: '#000' },
  overlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.5)', justifyContent: 'center', alignItems: 'center' },
  scanFrame: { width: 220, height: 220, borderWidth: 2, borderColor: '#2E9081', borderRadius: 30, marginBottom: 40 },
  closeScanner: { backgroundColor: '#FFF', paddingHorizontal: 30, paddingVertical: 12, borderRadius: 25 },
  closeScannerText: { color: '#000', fontWeight: '900' }
});